### ISSUE TITLE
Error with Redirect middleware

### ISSUE THREAD

**Issue by seregazhuk** [friends-of-reactphp/http-middleware-psr15-adapter#3]
I've tried your example from Readme as it is. Here is the code:
```php
$loop = Factory::create();
$server = new Server([
    new PSR15Middleware(
        $loop,
        \Middlewares\Redirect::class,
        [
            ['/old-url' => '/new-url']
        ],
        function ($redirectMiddleware) {
            return $redirectMiddleware
                ->permanent(false)
                ->query(false)
                ->method(['GET', 'POST']);
        }
    ),
    function(\Psr\Http\Message\RequestInterface $request){
        return new \React\Http\Response(200);
    }
]);


$socket = new \React\Socket\Server('127.0.0.1:8000', $loop);
$server->listen($socket);

echo 'Listening on ' . str_replace('tcp:', 'http:', $socket->getAddress()) . PHP_EOL;
$loop->run();
```

But when trying to request `http://127.0.0.1:8000/old-url` I receive 500, and the server script is running and reports nothing to the console. Also the same is true for `GroupedPSR15Middleware`. Can you suggest any ways to debug it?

**Comment by WyriHaximus** [comment]
After adding this to the example to get the error:
```
$server->on('error', function ($et) {
    echo (string)$et;
});
```

It turns out that middleware also needs `middlewares/utils` to be installed. I'll open an issue on the redirect middleware repo about this.

**Comment by seregazhuk** [comment]
Oh, I see. Thank you for quick response!

**Comment by WyriHaximus** [comment]
FYI is has just been fixed upstream https://github.com/middlewares/redirect/issues/3#issuecomment-355855651

**Comment by seregazhuk** [comment]
Great! Thanks 🎉
